name: exap
version: 0.0.1
descriptio: >-
  Eexample of using the package to generate 
  proto files `d2p_gen'.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  protobuf: ^3.0.0
  grpc: ^3.2.4


dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  d2p_gen:
    path: ../../d2p_gen/
  d2p_annotation:
    path: ../../d2p_annotation/
  freezed_annotation: ^2.4.1

