targets:
  # $default:
    # sources:
    #   - lib/**
    #   - src/**
    #   - test/**
    #   - bin/**
    #   - web/**
    #   - $package$
    #   - "benchmark/**"

  d2p_gen:d2p_gen:
    builders:
      d2p_gen:tmpProto:
        # generate_for:
        #   - lib/**.dart
        #   - src/**.dart
        #   - bin/**.dart

        options:
          enableLog: false
          rootProto: proto

      d2p_gen:finalizerProto:
        enabled: true
        options:
          enableLog: false

      d2p_gen:protocRunner:
        enabled: true
        options:
          enableLog: false

      d2p_gen:tmpMapper:
        enabled: true
        options:
          enableLog: false

      d2p_gen:sbuilder:
        enabled: true
        options:
          enableLog: false

      d2p_gen:testBuildet:
        enabled: true
        generate_for:
          - test/unit_testing/**_test.dart
        options:
          enableLog: false

builders:


  tmpProto:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "tmpProto"
    build_to: cache
    auto_apply: dependents
    build_extensions:
      .dart:
        - .tmp_proto
        - "{{}}.tmp_proto"
    runs_before:
      - finalizerProto
    defaults:
      generate_for:
        # include:
        #   - lib/**.dart
        #   - src/**.dart
        #   - bin/**.dart
        exclude:
          - .freezed.dart

  finalizerProto:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "finalizerProto"
    build_to: source
    auto_apply: dependents
    required_inputs:
      - "{{}}.tmp_proto"
    build_extensions:
      $package$:
        - messages.g.proto
    runs_before:
      - protocRunner

  protocRunner:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "protocRunner"
    build_to: cache
    auto_apply: dependents
    required_inputs:
      - messages.g.proto
    build_extensions:
      $package$:
        - .tmp1
        - .t
    runs_before:
      - tmpMapper

  tmpMapper:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "tmpMapper"
    build_to: source
    auto_apply: root_package
    required_inputs:
      - .tmp1
    build_extensions:
      $lib$:
        - "**/*.mp.dart"
        - .tmp2
    runs_before:
      # - testBuildet
      - sbuilder

  sbuilder:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "sbuilder"
    build_to: source
    auto_apply: dependents
    required_inputs:
      - .tmp2
    build_extensions:
      $package$:
        - ".skip"
    runs_before:
      - testBuildet

  testBuildet:
    import: "package:d2p_gen/d2p_gen.dart"
    builder_factories:
      - "testBuildet"
    build_to: source
    auto_apply: dependents
    required_inputs:
      - "{{}}.mp.dart"
    build_extensions:
      $package$:
        - "test/unit_testing/{{}}_test.dart"
    defaults:
      generate_for:
        # include:
        #   - lib/**.dart
        exclude:
          - .freezed.dart
