name: d2p_gen
description: >-
  This package creates messages for .proto based on existing dart 
  classes through recursive traversal of AST nodes . 
  If necessary, creates mappers for DTO classes (obtained through 
  the protocol utility, which runs automatically).
version: 0.0.1
homepage: https://github.com/Awesome-T/d2p_gen
repository: https://github.com/Awesome-T/d2p_gen
issue_tracker: https://github.com/Awesome-T/d2p_gen/issues
documentation: https://github.com/Awesome-T/d2p_gen
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  build: any
  source_gen: ^1.5.0
  d2p_annotation:
    path: ../d2p_annotation/
  analyzer: ^6.4.1
  glob: any
dev_dependencies:
  build_runner: ^2.3.3
  build_test: 
  lint: ^2.3.0
  mocktail: ^1.0.3
  # very_good_analysis: ^5.1.0

  test: any
topics:
  - network
  - proto
  - build_runner
  - code_gen
